[package]
name = "license-validator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
rsa = { version = "0.9", features = ["sha2", "pem", "getrandom"] }
sha2 = "0.10"
pem = "3.0"
base64 = "0.21"
getrandom = { version = "0.2", features = ["js"] }