/**
 * Category keyword mapping for news categorization
 * English language keywords that identify news categories
 */

export const categoryKeywords: Record<string, string[]> = {
  Politics: [
    'politics',
    'government',
    'election',
    'vote',
    'president',
    'parliament',
    'senate',
    'congress',
    'minister',
    'policy',
    'diplomatic',
    'legislation',
    'campaign',
    'democracy',
    'republican',
    'democrat',
    'liberal',
    'conservative',
    'party',
    'referendum',
    // Magyar kulcsszavak hozzáadása
    'politika',
    'kormány',
    'választás',
    'szavazás',
    'elnök',
    'miniszterelnök',
    'országgyűlés',
    'parlament',
    'miniszter',
    'rendelet',
    'törvény',
    'kampány',
    'demokrácia',
    'köztársaság',
    'párt',
    'népszavazás',
    'önkormányzat',
    'belpolitika',
    'külpolitika',
    'ellenzék',
    'kormánypárt',
  ],
  Economy: [
    'economy',
    'economic',
    'finance',
    'market',
    'stock',
    'trade',
    'inflation',
    'recession',
    'gdp',
    'growth',
    'unemployment',
    'interest rate',
    'fiscal',
    'monetary',
    'debt',
    'budget',
    'investment',
    'banking',
    'financial',
    'currency',
  ],
  Business: [
    'business',
    'company',
    'corporate',
    'industry',
    'firm',
    'startup',
    'enterprise',
    'ceo',
    'profit',
    'merger',
    'acquisition',
    'shares',
    'stock market',
    'investor',
    'commercial',
    'revenue',
    'corporation',
    'entrepreneur',
    'venture',
    'retail',
  ],
  Sports: [
    'sports',
    'football',
    'soccer',
    'basketball',
    'tennis',
    'olympics',
    'championship',
    'tournament',
    'match',
    'game',
    'player',
    'team',
    'coach',
    'athlete',
    'league',
    'formula',
    'racing',
    'score',
    'win',
    'competition',
  ],
  World: [
    'world',
    'international',
    'global',
    'foreign',
    'overseas',
    'diplomatic',
    'relations',
    'country',
    'nations',
    'summit',
    'treaty',
    'united nations',
    'un',
    'nato',
    'eu',
    'crisis',
    'conflict',
    'embassy',
    'bilateral',
    'multilateral',
  ],
  Education: [
    'education',
    'school',
    'university',
    'college',
    'student',
    'teacher',
    'professor',
    'academic',
    'study',
    'research',
    'learning',
    'degree',
    'campus',
    'curriculum',
    'scholarship',
    'classroom',
    'graduate',
    'undergraduate',
    'faculty',
    'lecture',
  ],
  Environment: [
    'environment',
    'climate',
    'green',
    'sustainable',
    'ecology',
    'pollution',
    'carbon',
    'emissions',
    'renewable',
    'conservation',
    'wildlife',
    'energy',
    'fossil fuel',
    'recycling',
    'biodiversity',
    'forest',
    'ocean',
    'natural resources',
    'ecosystem',
    'global warming',
  ],
  Technology: [
    'technology',
    'tech',
    'innovation',
    'digital',
    'software',
    'hardware',
    'internet',
    'computer',
    'ai',
    'artificial intelligence',
    'app',
    'cyber',
    'robot',
    'automation',
    'smartphone',
    'device',
    'data',
    'computing',
    'algorithm',
    'programming',
  ],
  Health: [
    'health',
    'medical',
    'doctor',
    'hospital',
    'patient',
    'disease',
    'virus',
    'treatment',
    'medicine',
    'healthcare',
    'pandemic',
    'vaccine',
    'drug',
    'surgery',
    'illness',
    'wellness',
    'therapy',
    'clinical',
    'research',
    'diagnosis',
  ],
};

// Export a default list of categories that should always be shown
export const defaultCategories = [
  'Politics',
  'Economy',
  'Business',
  'Sports',
  'World',
  'Education',
  'Environment',
  'Technology',
  'Health',
];
