/**
 * Kontinensek és országok adatbázisa
 * Az országkódok ISO 3166-1 alpha-2 szabvány szerint
 */

export interface Country {
  name: string; // Az ország neve angolul
  code: string; // ISO 3166-1 alpha-2 országkód
  native?: string; // Az ország neve saját nyelvén (opcionális)
}

export interface Continent {
  name: string; // A kontinens neve angolul
  code: string; // Kontinens azonosító
  countries: Country[];
}

export const CONTINENTS: Continent[] = [
  {
    name: 'Europe',
    code: 'EU',
    countries: [
      { name: 'Albania', code: 'AL', native: 'Shqipëria' },
      { name: 'Andorra', code: 'AD', native: 'Andorra' },
      { name: 'Austria', code: 'AT', native: 'Österreich' },
      { name: 'Belarus', code: 'BY', native: 'Беларусь' },
      { name: 'Belgium', code: 'BE', native: 'België/Belgique' },
      { name: 'Bosnia and Herzegovina', code: 'BA', native: 'Bosna i Hercegovina' },
      { name: 'Bulgaria', code: 'BG', native: 'България' },
      { name: 'Croatia', code: 'HR', native: 'Hrvatska' },
      { name: 'Cyprus', code: 'CY', native: 'Κύπρος' },
      { name: 'Czech Republic', code: 'CZ', native: 'Česko' },
      { name: 'Denmark', code: 'DK', native: 'Danmark' },
      { name: 'Estonia', code: 'EE', native: 'Eesti' },
      { name: 'Finland', code: 'FI', native: 'Suomi' },
      { name: 'France', code: 'FR', native: 'France' },
      { name: 'Germany', code: 'DE', native: 'Deutschland' },
      { name: 'Greece', code: 'GR', native: 'Ελλάδα' },
      { name: 'Hungary', code: 'HU', native: 'Magyarország' },
      { name: 'Iceland', code: 'IS', native: 'Ísland' },
      { name: 'Ireland', code: 'IE', native: 'Éire' },
      { name: 'Italy', code: 'IT', native: 'Italia' },
      { name: 'Latvia', code: 'LV', native: 'Latvija' },
      { name: 'Liechtenstein', code: 'LI', native: 'Liechtenstein' },
      { name: 'Lithuania', code: 'LT', native: 'Lietuva' },
      { name: 'Luxembourg', code: 'LU', native: 'Luxembourg' },
      { name: 'Malta', code: 'MT', native: 'Malta' },
      { name: 'Moldova', code: 'MD', native: 'Moldova' },
      { name: 'Monaco', code: 'MC', native: 'Monaco' },
      { name: 'Montenegro', code: 'ME', native: 'Црна Гора' },
      { name: 'Netherlands', code: 'NL', native: 'Nederland' },
      { name: 'North Macedonia', code: 'MK', native: 'Северна Македонија' },
      { name: 'Norway', code: 'NO', native: 'Norge' },
      { name: 'Poland', code: 'PL', native: 'Polska' },
      { name: 'Portugal', code: 'PT', native: 'Portugal' },
      { name: 'Romania', code: 'RO', native: 'România' },
      { name: 'Russia', code: 'RU', native: 'Россия' },
      { name: 'San Marino', code: 'SM', native: 'San Marino' },
      { name: 'Serbia', code: 'RS', native: 'Србија' },
      { name: 'Slovakia', code: 'SK', native: 'Slovensko' },
      { name: 'Slovenia', code: 'SI', native: 'Slovenija' },
      { name: 'Spain', code: 'ES', native: 'España' },
      { name: 'Sweden', code: 'SE', native: 'Sverige' },
      { name: 'Switzerland', code: 'CH', native: 'Schweiz' },
      { name: 'Ukraine', code: 'UA', native: 'Україна' },
      { name: 'United Kingdom', code: 'GB', native: 'United Kingdom' },
      { name: 'Vatican City', code: 'VA', native: 'Status Civitatis Vaticanæ' },
    ],
  },
  {
    name: 'Asia',
    code: 'AS',
    countries: [
      { name: 'Afghanistan', code: 'AF', native: 'افغانستان' },
      { name: 'Armenia', code: 'AM', native: 'Հայաստան' },
      { name: 'Azerbaijan', code: 'AZ', native: 'Azərbaycan' },
      { name: 'Bahrain', code: 'BH', native: 'البحرين' },
      { name: 'Bangladesh', code: 'BD', native: 'বাংলাদেশ' },
      { name: 'Bhutan', code: 'BT', native: 'འབྲུག་ཡུལ' },
      { name: 'Brunei', code: 'BN', native: 'Brunei Darussalam' },
      { name: 'Cambodia', code: 'KH', native: 'កម្ពុជា' },
      { name: 'China', code: 'CN', native: '中国' },
      { name: 'Georgia', code: 'GE', native: 'საქართველო' },
      { name: 'India', code: 'IN', native: 'भारत' },
      { name: 'Indonesia', code: 'ID', native: 'Indonesia' },
      { name: 'Iran', code: 'IR', native: 'ایران' },
      { name: 'Iraq', code: 'IQ', native: 'العراق' },
      { name: 'Israel', code: 'IL', native: 'ישראל' },
      { name: 'Japan', code: 'JP', native: '日本' },
      { name: 'Jordan', code: 'JO', native: 'الأردن' },
      { name: 'Kazakhstan', code: 'KZ', native: 'Қазақстан' },
      { name: 'South Korea', code: 'KR', native: '대한민국' },
      { name: 'Kuwait', code: 'KW', native: 'الكويت' },
      { name: 'Malaysia', code: 'MY', native: 'Malaysia' },
      { name: 'Mongolia', code: 'MN', native: 'Монгол улс' },
      { name: 'Nepal', code: 'NP', native: 'नेपाल' },
      { name: 'Oman', code: 'OM', native: 'عمان' },
      { name: 'Pakistan', code: 'PK', native: 'پاکستان' },
      { name: 'Philippines', code: 'PH', native: 'Pilipinas' },
      { name: 'United Arab Emirates', code: 'AE', native: 'الإمارات العربية المتحدة' },
      { name: 'Laos', code: 'LA', native: 'ລາວ' },
      { name: 'Lebanon', code: 'LB', native: 'لبنان' },
      { name: 'Maldives', code: 'MV', native: 'Dhivehi Raajje' },
      { name: 'Myanmar', code: 'MM', native: 'မြန်မာ' },
      { name: 'North Korea', code: 'KP', native: '조선민주주의인민공화국' },
      { name: 'Qatar', code: 'QA', native: 'قطر' },
      { name: 'Saudi Arabia', code: 'SA', native: 'السعودية' },
      { name: 'Singapore', code: 'SG', native: 'Singapore' },
      { name: 'Sri Lanka', code: 'LK', native: 'ශ්‍රී ලංකාව' },
      { name: 'Syria', code: 'SY', native: 'سوريا' },
      { name: 'Taiwan', code: 'TW', native: '臺灣' },
      { name: 'Tajikistan', code: 'TJ', native: 'Тоҷикистон' },
      { name: 'Thailand', code: 'TH', native: 'ประเทศไทย' },
      { name: 'Timor-Leste', code: 'TL', native: 'Timor-Leste' },
      { name: 'Turkey', code: 'TR', native: 'Türkiye' },
      { name: 'Turkmenistan', code: 'TM', native: 'Türkmenistan' },
      { name: 'Uzbekistan', code: 'UZ', native: "O'zbekiston" },
      { name: 'Vietnam', code: 'VN', native: 'Việt Nam' },
      { name: 'Yemen', code: 'YE', native: 'اليمن' },
      { name: 'Palestine', code: 'PS', native: 'فلسطين' },
      { name: 'Kyrgyzstan', code: 'KG', native: 'Кыргызстан' },
    ],
  },
  {
    name: 'Africa',
    code: 'AF',
    countries: [
      { name: 'Algeria', code: 'DZ', native: 'الجزائر' },
      { name: 'Angola', code: 'AO', native: 'Angola' },
      { name: 'Benin', code: 'BJ', native: 'Bénin' },
      { name: 'Botswana', code: 'BW', native: 'Botswana' },
      { name: 'Burkina Faso', code: 'BF', native: 'Burkina Faso' },
      { name: 'Burundi', code: 'BI', native: 'Burundi' },
      { name: 'Cameroon', code: 'CM', native: 'Cameroun' },
      { name: 'Cape Verde', code: 'CV', native: 'Cabo Verde' },
      { name: 'Central African Republic', code: 'CF', native: 'République Centrafricaine' },
      { name: 'Chad', code: 'TD', native: 'Tchad' },
      { name: 'Comoros', code: 'KM', native: 'Komori' },
      { name: 'Congo', code: 'CG', native: 'République du Congo' },
      { name: 'DR Congo', code: 'CD', native: 'République démocratique du Congo' },
      { name: 'Djibouti', code: 'DJ', native: 'Djibouti' },
      { name: 'Egypt', code: 'EG', native: 'مصر' },
      { name: 'Equatorial Guinea', code: 'GQ', native: 'Guinea Ecuatorial' },
      { name: 'Eritrea', code: 'ER', native: 'ኤርትራ' },
      { name: 'Ethiopia', code: 'ET', native: 'ኢትዮጵያ' },
      { name: 'Gabon', code: 'GA', native: 'Gabon' },
      { name: 'Gambia', code: 'GM', native: 'The Gambia' },
      { name: 'Ghana', code: 'GH', native: 'Ghana' },
      { name: 'Guinea', code: 'GN', native: 'Guinée' },
      { name: 'Guinea-Bissau', code: 'GW', native: 'Guiné-Bissau' },
      { name: 'Ivory Coast', code: 'CI', native: "Côte d'Ivoire" },
      { name: 'Kenya', code: 'KE', native: 'Kenya' },
      { name: 'Lesotho', code: 'LS', native: 'Lesotho' },
      { name: 'Liberia', code: 'LR', native: 'Liberia' },
      { name: 'Libya', code: 'LY', native: 'ليبيا' },
      { name: 'Madagascar', code: 'MG', native: 'Madagasikara' },
      { name: 'Malawi', code: 'MW', native: 'Malawi' },
      { name: 'Mali', code: 'ML', native: 'Mali' },
      { name: 'Mauritania', code: 'MR', native: 'موريتانيا' },
      { name: 'Mauritius', code: 'MU', native: 'Mauritius' },
      { name: 'Morocco', code: 'MA', native: 'المغرب' },
      { name: 'Mozambique', code: 'MZ', native: 'Moçambique' },
      { name: 'Namibia', code: 'NA', native: 'Namibia' },
      { name: 'Niger', code: 'NE', native: 'Niger' },
      { name: 'Nigeria', code: 'NG', native: 'Nigeria' },
      { name: 'Rwanda', code: 'RW', native: 'Rwanda' },
      { name: 'Sao Tome and Principe', code: 'ST', native: 'São Tomé e Príncipe' },
      { name: 'Senegal', code: 'SN', native: 'Sénégal' },
      { name: 'Seychelles', code: 'SC', native: 'Seychelles' },
      { name: 'Sierra Leone', code: 'SL', native: 'Sierra Leone' },
      { name: 'Somalia', code: 'SO', native: 'Soomaaliya' },
      { name: 'South Africa', code: 'ZA', native: 'South Africa' },
      { name: 'South Sudan', code: 'SS', native: 'South Sudan' },
      { name: 'Sudan', code: 'SD', native: 'السودان' },
      { name: 'Swaziland', code: 'SZ', native: 'Swaziland' },
      { name: 'Tanzania', code: 'TZ', native: 'Tanzania' },
      { name: 'Togo', code: 'TG', native: 'Togo' },
      { name: 'Tunisia', code: 'TN', native: 'تونس' },
      { name: 'Uganda', code: 'UG', native: 'Uganda' },
      { name: 'Zambia', code: 'ZM', native: 'Zambia' },
      { name: 'Zimbabwe', code: 'ZW', native: 'Zimbabwe' },
    ],
  },
  {
    name: 'North America',
    code: 'NA',
    countries: [
      { name: 'Canada', code: 'CA', native: 'Canada' },
      { name: 'Mexico', code: 'MX', native: 'México' },
      { name: 'United States', code: 'US', native: 'United States' },
      { name: 'Costa Rica', code: 'CR', native: 'Costa Rica' },
      { name: 'Cuba', code: 'CU', native: 'Cuba' },
      { name: 'El Salvador', code: 'SV', native: 'El Salvador' },
      { name: 'Guatemala', code: 'GT', native: 'Guatemala' },
      { name: 'Haiti', code: 'HT', native: 'Haïti' },
      { name: 'Honduras', code: 'HN', native: 'Honduras' },
      { name: 'Jamaica', code: 'JM', native: 'Jamaica' },
      { name: 'Nicaragua', code: 'NI', native: 'Nicaragua' },
      { name: 'Panama', code: 'PA', native: 'Panamá' },
      { name: 'Antigua and Barbuda', code: 'AG', native: 'Antigua and Barbuda' },
      { name: 'Bahamas', code: 'BS', native: 'Bahamas' },
      { name: 'Barbados', code: 'BB', native: 'Barbados' },
      { name: 'Belize', code: 'BZ', native: 'Belize' },
      { name: 'Dominica', code: 'DM', native: 'Dominica' },
      { name: 'Dominican Republic', code: 'DO', native: 'República Dominicana' },
      { name: 'Grenada', code: 'GD', native: 'Grenada' },
      { name: 'Saint Kitts and Nevis', code: 'KN', native: 'Saint Kitts and Nevis' },
      { name: 'Saint Lucia', code: 'LC', native: 'Saint Lucia' },
      {
        name: 'Saint Vincent and the Grenadines',
        code: 'VC',
        native: 'Saint Vincent and the Grenadines',
      },
      { name: 'Trinidad and Tobago', code: 'TT', native: 'Trinidad and Tobago' },
      { name: 'Puerto Rico', code: 'PR', native: 'Puerto Rico' },
      { name: 'Greenland', code: 'GL', native: 'Kalaallit Nunaat' },
    ],
  },
  {
    name: 'South America',
    code: 'SA',
    countries: [
      { name: 'Argentina', code: 'AR', native: 'Argentina' },
      { name: 'Bolivia', code: 'BO', native: 'Bolivia' },
      { name: 'Brazil', code: 'BR', native: 'Brasil' },
      { name: 'Chile', code: 'CL', native: 'Chile' },
      { name: 'Colombia', code: 'CO', native: 'Colombia' },
      { name: 'Ecuador', code: 'EC', native: 'Ecuador' },
      { name: 'Guyana', code: 'GY', native: 'Guyana' },
      { name: 'Paraguay', code: 'PY', native: 'Paraguay' },
      { name: 'Peru', code: 'PE', native: 'Perú' },
      { name: 'Suriname', code: 'SR', native: 'Suriname' },
      { name: 'Uruguay', code: 'UY', native: 'Uruguay' },
      { name: 'Venezuela', code: 'VE', native: 'Venezuela' },
      { name: 'French Guiana', code: 'GF', native: 'Guyane française' },
    ],
  },
  {
    name: 'Oceania',
    code: 'OC',
    countries: [
      { name: 'Australia', code: 'AU', native: 'Australia' },
      { name: 'Fiji', code: 'FJ', native: 'Fiji' },
      { name: 'New Zealand', code: 'NZ', native: 'New Zealand' },
      { name: 'Papua New Guinea', code: 'PG', native: 'Papua New Guinea' },
      { name: 'Samoa', code: 'WS', native: 'Samoa' },
      { name: 'Tonga', code: 'TO', native: 'Tonga' },
      { name: 'Vanuatu', code: 'VU', native: 'Vanuatu' },
      { name: 'Kiribati', code: 'KI', native: 'Kiribati' },
      { name: 'Marshall Islands', code: 'MH', native: 'Marshall Islands' },
      { name: 'Micronesia', code: 'FM', native: 'Federated States of Micronesia' },
      { name: 'Nauru', code: 'NR', native: 'Nauru' },
      { name: 'Palau', code: 'PW', native: 'Palau' },
      { name: 'Solomon Islands', code: 'SB', native: 'Solomon Islands' },
      { name: 'Tuvalu', code: 'TV', native: 'Tuvalu' },
      { name: 'Cook Islands', code: 'CK', native: 'Cook Islands' },
      { name: 'Niue', code: 'NU', native: 'Niue' },
      { name: 'French Polynesia', code: 'PF', native: 'Polynésie française' },
      { name: 'New Caledonia', code: 'NC', native: 'Nouvelle-Calédonie' },
    ],
  },
];

// Segédfüggvények
export const findCountryByCode = (code: string): Country | undefined => {
  for (const continent of CONTINENTS) {
    const country = continent.countries.find((c) => c.code === code);
    if (country) return country;
  }
  return undefined;
};

export const findContinentByCountryCode = (code: string): Continent | undefined => {
  return CONTINENTS.find((continent) =>
    continent.countries.some((country) => country.code === code),
  );
};

// Összes ország lekérdezése egy tömbben
export const getAllCountries = (): Country[] => {
  return CONTINENTS.flatMap((continent) => continent.countries);
};
