/**
 * Ország mappingek és normalizálók
 * Kiszervezve a Location.ts fájlból a jobb szervezés érdekében
 */

export const countryMapping: Record<string, string> = {
  Hungary: 'Hungary (HU)',
  Germany: 'Germany (DE)',
  France: 'France (FR)',
  'United Kingdom': 'United Kingdom (GB)',
  Italy: 'Italy (IT)',
  Spain: 'Spain (ES)',
  Poland: 'Poland (PL)',
  Netherlands: 'Netherlands (NL)',
  Belgium: 'Belgium (BE)',
  Austria: 'Austria (AT)',
  Switzerland: 'Switzerland (CH)',
  Sweden: 'Sweden (SE)',
  Norway: 'Norway (NO)',
  Finland: 'Finland (FI)',
  Denmark: 'Denmark (DK)',
  'Czech Republic': 'Czech Republic (CZ)',
  Slovakia: 'Slovakia (SK)',
  Romania: 'Romania (RO)',
  Bulgaria: 'Bulgaria (BG)',
  Croatia: 'Croatia (HR)',
  'United States': 'United States (US)',
  Canada: 'Canada (CA)',
  Mexico: 'Mexico (MX)',
  Brazil: 'Brazil (BR)',
  Argentina: 'Argentina (AR)',
  Chile: 'Chile (CL)',
  Colombia: 'Colombia (CO)',
  Peru: 'Peru (PE)',
  Venezuela: 'Venezuela (VE)',
  Australia: 'Australia (AU)',
  'New Zealand': 'New Zealand (NZ)',
  China: 'China (CN)',
  Japan: 'Japan (JP)',
  'South Korea': 'South Korea (KR)',
  India: 'India (IN)',
  Thailand: 'Thailand (TH)',
  Singapore: 'Singapore (SG)',
  Malaysia: 'Malaysia (MY)',
  Indonesia: 'Indonesia (ID)',
  Philippines: 'Philippines (PH)',
  Vietnam: 'Vietnam (VN)',
  Cambodia: 'Cambodia (KH)',
  'South Africa': 'South Africa (ZA)',
  Nigeria: 'Nigeria (NG)',
  Kenya: 'Kenya (KE)',
  Egypt: 'Egypt (EG)',
  Morocco: 'Morocco (MA)',
  Algeria: 'Algeria (DZ)',
  Tunisia: 'Tunisia (TN)',
  Ghana: 'Ghana (GH)',
};

export const countryNormalizers: Record<string, string[]> = {
  Hungary: ['Hungary', 'Hungary (HU)', 'HU', 'Magyar', 'Magyarország'],
  Germany: ['Germany', 'Germany (DE)', 'DE', 'Deutschland', 'Németország'],
  France: ['France', 'France (FR)', 'FR', 'Franciaország'],
  'United Kingdom': [
    'United Kingdom',
    'United Kingdom (GB)',
    'GB',
    'UK',
    'Britain',
    'England',
    'Egyesült Királyság',
  ],
  Italy: ['Italy', 'Italy (IT)', 'IT', 'Italia', 'Olaszország'],
  Spain: ['Spain', 'Spain (ES)', 'ES', 'España', 'Spanyolország'],
  Poland: ['Poland', 'Poland (PL)', 'PL', 'Polska', 'Lengyelország'],
  Netherlands: ['Netherlands', 'Netherlands (NL)', 'NL', 'Holland', 'Hollandia'],
  Belgium: ['Belgium', 'Belgium (BE)', 'BE', 'België', 'Belgique', 'Belgium'],
  Austria: ['Austria', 'Austria (AT)', 'AT', 'Österreich', 'Ausztria'],
  Switzerland: [
    'Switzerland',
    'Switzerland (CH)',
    'CH',
    'Schweiz',
    'Suisse',
    'Svizzera',
    'Svizra',
    'Svájc',
  ],
  Sweden: ['Sweden', 'Sweden (SE)', 'SE', 'Sverige', 'Svédország'],
  Norway: ['Norway', 'Norway (NO)', 'NO', 'Norge', 'Norvégia'],
  Finland: ['Finland', 'Finland (FI)', 'FI', 'Suomi', 'Finnország'],
  Denmark: ['Denmark', 'Denmark (DK)', 'DK', 'Danmark', 'Dánia'],
  'Czech Republic': [
    'Czech Republic',
    'Czech Republic (CZ)',
    'CZ',
    'Czechia',
    'Česká republika',
    'Csehország',
  ],
  Slovakia: ['Slovakia', 'Slovakia (SK)', 'SK', 'Slovensko', 'Szlovákia'],
  Romania: ['Romania', 'Romania (RO)', 'RO', 'România', 'Románia'],
  Bulgaria: ['Bulgaria', 'Bulgaria (BG)', 'BG', 'България', 'Bulgária'],
  Croatia: ['Croatia', 'Croatia (HR)', 'HR', 'Hrvatska', 'Horvátország'],
  'United States': [
    'United States',
    'United States (US)',
    'US',
    'USA',
    'America',
    'Egyesült Államok',
  ],
  Canada: ['Canada', 'Canada (CA)', 'CA', 'Kanada'],
  Mexico: ['Mexico', 'Mexico (MX)', 'MX', 'México', 'Mexikó'],
  Brazil: ['Brazil', 'Brazil (BR)', 'BR', 'Brasil', 'Brazília'],
  Argentina: ['Argentina', 'Argentina (AR)', 'AR', 'Argentína'],
  Chile: ['Chile', 'Chile (CL)', 'CL', 'Chili'],
  Colombia: ['Colombia', 'Colombia (CO)', 'CO', 'Kolumbia'],
  Peru: ['Peru', 'Peru (PE)', 'PE', 'Perú'],
  Venezuela: ['Venezuela', 'Venezuela (VE)', 'VE'],
  Australia: ['Australia', 'Australia (AU)', 'AU', 'Ausztrália'],
  'New Zealand': ['New Zealand', 'New Zealand (NZ)', 'NZ', 'Új-Zéland'],
  China: ['China', 'China (CN)', 'CN', '中国', 'Kína'],
  Japan: ['Japan', 'Japan (JP)', 'JP', '日本', 'Japán'],
  'South Korea': ['South Korea', 'South Korea (KR)', 'KR', '한국', 'Dél-Korea'],
  India: ['India', 'India (IN)', 'IN', 'भारत', 'India'],
  Thailand: ['Thailand', 'Thailand (TH)', 'TH', 'ไทย', 'Thaiföld'],
  Singapore: ['Singapore', 'Singapore (SG)', 'SG', 'Szingapúr'],
  Malaysia: ['Malaysia', 'Malaysia (MY)', 'MY', 'Malajzia'],
  Indonesia: ['Indonesia', 'Indonesia (ID)', 'ID', 'Indonézia'],
  Philippines: ['Philippines', 'Philippines (PH)', 'PH', 'Filipínuszi-szigetek'],
  Vietnam: ['Vietnam', 'Vietnam (VN)', 'VN', 'Việt Nam', 'Vietnam'],
  Cambodia: ['Cambodia', 'Cambodia (KH)', 'KH', 'កម្ពុជា', 'Kambodzsa'],
  'South Africa': ['South Africa', 'South Africa (ZA)', 'ZA', 'Dél-Afrika'],
  Nigeria: ['Nigeria', 'Nigeria (NG)', 'NG', 'Nigéria'],
  Kenya: ['Kenya', 'Kenya (KE)', 'KE', 'Kénia'],
  Egypt: ['Egypt', 'Egypt (EG)', 'EG', 'مصر', 'Egyiptom'],
  Morocco: ['Morocco', 'Morocco (MA)', 'MA', 'المغرب', 'Marokkó'],
  Algeria: ['Algeria', 'Algeria (DZ)', 'DZ', 'الجزائر', 'Algéria'],
  Tunisia: ['Tunisia', 'Tunisia (TN)', 'TN', 'تونس', 'Tunézia'],
  Ghana: ['Ghana', 'Ghana (GH)', 'GH', 'Ghána'],
};

export const countryCodeNameMap: Record<string, string> = {
  hu: 'Magyarország',
  gb: 'Egyesült Királyság',
  uk: 'Egyesült Királyság',
  de: 'Németország',
  fr: 'Franciaország',
  it: 'Olaszország',
  es: 'Spanyolország',
  pl: 'Lengyelország',
  nl: 'Hollandia',
  be: 'Belgium',
  at: 'Ausztria',
  ch: 'Svájc',
  se: 'Svédország',
  no: 'Norvégia',
  fi: 'Finnország',
  dk: 'Dánia',
  cz: 'Csehország',
  sk: 'Szlovákia',
  ro: 'Románia',
  bg: 'Bulgária',
  hr: 'Horvátország',
  us: 'Egyesült Államok',
  ca: 'Kanada',
  mx: 'Mexikó',
  br: 'Brazília',
  ar: 'Argentína',
  cl: 'Chile',
  co: 'Kolumbia',
  pe: 'Peru',
  ve: 'Venezuela',
  au: 'Ausztrália',
  nz: 'Új-Zéland',
  cn: 'Kína',
  jp: 'Japán',
  kr: 'Dél-Korea',
  in: 'India',
  th: 'Thaiföld',
  sg: 'Szingapúr',
  my: 'Malajzia',
  id: 'Indonézia',
  ph: 'Fülöp-szigetek',
  vn: 'Vietnam',
  kh: 'Kambodzsa',
  za: 'Dél-Afrika',
  ng: 'Nigéria',
  ke: 'Kénia',
  eg: 'Egyiptom',
  ma: 'Marokkó',
  dz: 'Algéria',
  tn: 'Tunézia',
  gh: 'Ghána',
};

export const continentCountryCodes = {
  asia: ['cn', 'jp', 'kr', 'in', 'th', 'sg', 'my', 'id', 'ph', 'vn', 'kh'],
  africa: ['za', 'ng', 'ke', 'eg', 'ma', 'dz', 'tn', 'gh'],
  northAmerica: ['us', 'ca', 'mx'],
  southAmerica: ['br', 'ar', 'cl', 'co', 'pe', 've'],
  oceania: ['au', 'nz'],
  europe: [
    'hu',
    'gb',
    'uk',
    'de',
    'fr',
    'it',
    'es',
    'at',
    'ch',
    'nl',
    'be',
    'pl',
    'se',
    'no',
    'fi',
    'dk',
    'cz',
    'sk',
    'ro',
    'bg',
    'hr',
  ],
};
